#include <stdio.h>

#include <porphyrin.h>

VSAPI api {
    createCore,
    freeCore,
    getCoreInfo,
    cloneFrameRef,
    cloneNodeRef,
    cloneFuncRef,
    freeFrame,
    freeNode,
    freeFunc,
    newVideoFrame,
    copyFrame,
    copyFrameProps,
    nullptr, // registerFunction,
    nullptr, // getPluginById,
    nullptr, // getPluginByNs,
    nullptr, // getPlugins,
    nullptr, // getFunctions,
    nullptr, // createFilter,
    setError,
    getError,
    nullptr, // setFilterError,
    nullptr, // invoke,
    getFormatPreset,
    registerFormat,
    getFrame,
    getFrameAsync,
    getFrameFilter,
    requestFrameFilter,
    nullptr, // queryCompletedFrame,
    nullptr, // releaseFrameEarly,
    getStride,
    getReadPtr,
    getWritePtr,
    createFunc,
    callFunc,
    createMap,
    freeMap,
    clearMap,
    getVideoInfo,
    setVideoInfo,
    getFrameFormat,
    getFrameWidth,
    getFrameHeight,
    getFramePropsRO,
    getFramePropsRW,
    propNumKeys,
    propGetKey,
    propNumElements,
    propGetType,
    propGetInt,
    propGetFloat,
    propGetData,
    propGetDataSize,
    propGetNode,
    propGetFrame,
    propGetFunc,
    propDeleteKey,
    propSetInt,
    propSetFloat,
    propSetData,
    propSetNode,
    propSetFrame,
    propSetFunc,
    setMaxCacheSize,
    nullptr, // getOutputIndex,
    newVideoFrame2,
    setMessageHandler,
    setThreadCount,
    nullptr, // getPluginPath,
    propGetIntArray,
    propGetFloatArray,
    propSetIntArray,
    propSetFloatArray,
    logMessage,
    addMessageHandler,
    removeMessageHandler,
    getCoreInfo2,
};

VS_API(const VSAPI*) getVapourSynthAPI(int version) noexcept {
    if (version != VAPOURSYNTH_API_VERSION) {
        fprintf(stderr, "VapourSynth API version mismatch");
        abort();
    }
    return &api;
}
