name: Build

on: [push, workflow_dispatch]


jobs:
  build-windows:
    runs-on: windows-2022
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Setup PATH
      run: |
        $VSRoot = (vswhere -latest -property installationPath)
        Add-Content ("$VSRoot\VC\Tools\Llvm\x64\bin;$VSRoot\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin;$VSRoot\Common7\IDE\CommonExtensions\Microsoft\CMake\Ninja;" + $env:Path) -LiteralPath $env:GITHUB_PATH
    - name: Build Release
      run: |
        cmake --preset Release-Clang
        cmake --build --preset Release-Clang
